config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get '/calendar', to: 'static_pages#calendar'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]

  # Need Routes for all models 

  #Patient
  resources :patients do
    resources :appointments, only: [:index, :show, :new, :create]
    # Templates
    # Allows for /patient/:id/TEMPLATE
    get :appointment_confirmation, format: 'docx'
    get :depo_invoice, format: 'docx'
    get :depo_confirmation, format: 'docx'
    get :action_items, format: 'docx'
  end

  #Appointment
  resources :appointments

  #Attorney
  resources :attorneys

  #Adjuster
  #resources :adjuster

end

app/models/patient.rb
class Patient < ApplicationRecord
	
	# Relations
	has_many :appointments, inverse_of: :patient, dependent: :destroy 
	has_many :attorneys, inverse_of: :patient, dependent: :destroy
	has_many :adjusters, inverse_of: :patient, dependent: :destroy

	#Validations
	validates :ssn, uniqueness: true
	validates	:name, presence: true
	

	#Nested Edits
	accepts_nested_attributes_for :attorneys, allow_destroy: true
	accepts_nested_attributes_for :adjusters, allow_destroy: true


	# Search Function
	def self.search(search)
	  if search
	    where('name LIKE ?', "%#{search}%")
	  else
	    all
	  end
	end

	
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		if params[:search]
			@patients = Patient.search(params[:search]).paginate(page: params[:page], :per_page => 20)
		else
			@patients = Patient.paginate(page: params[:page],:per_page => 20)
		end
	end

	def show
		@patient = Patient.find(params[:id])
		@attorneys = @patient.attorneys.paginate(page: params[:page])
		@adjusters = @patient.adjusters.paginate(page: params[:page])
		@appointments = @patient.appointments.paginate(page: params[:page])
	end

	def new
		@patient = Patient.new
		@patient.attorneys.build
		@patient.adjusters.build
	end

	def create
		@patient = Patient.new(patient_params)
			if @patient.save
				flash[:info] = "Patient was added to the system"
				redirect_to @patient
			else
				render 'new'
			end
	end

	def edit
		@patient = Patient.find(params[:id])
		@attorneys = @patient.attorneys
		@adjusters = @patient.adjusters
	end

	def update
		@patient = Patient.find(params[:id])
		@attoryneys = @patient.attorneys
		if @patient.update_attributes(patient_params)
			flash[:success] = "Patient Updated"
			redirect_to @patient
		else
			render 'edit'
		end
	end

	def destroy
		Patient.find(params[:id]).destroy
		flash[:success] = "Patient Deleted"
		redirect_to patients_url
	end

	# Template Specific Actions for routing

	def appointment_confirmation
		@patient = Patient.find(params[:patient_id])
		@applicant_attorney = @patient.attorneys.where("attorney_type = 'Applicant'")
		@defense_attorney = @patient.attorneys.where("attorney_type = 'Defense'")

		respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"appointment_confirmation.docx\"" }
    end
	end


	def depo_invoice
		@patient = Patient.find(params[:patient_id])
		@applicant_attorney = @patient.attorneys.where("attorney_type = 'Applicant'")
		@defense_attorney = @patient.attorneys.where("attorney_type = 'Defense'")
		@depo_appointment = @patient.appointments.where("appointment_type = 'Deposition'")
		
		respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"depo_invoice.docx\"" }
    end
	end

	def depo_confirmation
		@patient = Patient.find(params[:patient_id])
		@applicant_attorney = @patient.attorneys.where("attorney_type = 'Applicant'")
		@defense_attorney = @patient.attorneys.where("attorney_type = 'Defense'")
		@depo_appointment = @patient.appointments.where("appointment_type = 'Deposition'")

		respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"depo_confirmation.docx\"" }
    end
	end

	def action_items
		@patient = Patient.find(params[:patient_id])

		respond_to do |format|
      format.docx { headers["Content-Disposition"] = "attachment; filename=\"action_items.docx\"" }
    end
	end


	private

	def patient_params
		params.require(:patient).permit(:name, :interpreter, :street_address, :city, :state, :zip_code, :phone, :ssn, :dob, :date_of_injury, :report_type, :employer, :claim_number, :panel_number, :wcab_number, :notes, 
			attorneys_attributes: [:id, :name, :firm, :address, :phone, :fax],
			adjusters_attributes: [:id, :name, :agency, :address, :phone, :fax])
	end

	def attorney_params
		params.require(:patient).permit(:name, :firm, :address, :phone, :fax)
	end

	def sort_column
		Patient.columns.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_patient.html.erb
	<tr>
		<td><%= patient.id %></td>
		<td><%= link_to patient.name, patient %></td>
		<td><%= patient.date_of_injury %></td>
		<td><%= patient.report_type %></td>
		<td><%= patient.updated_at.strftime("%D - %I:%M %P") %></td>
		<td><%= patient.created_at.strftime("%D - %I:%M %P") %></td>
	</tr>

app/views/patients/edit.html.erb
<% provide(:title, 'New Patient') %>
<h1>Update Patient Information:</h1>

<div class="row">
  <div class="col-md-4">
		<%= form_for(@patient) do |f| %>
      <%= render 'shared/patient_messages' %>

      <%= f.label :name, class: 'label-control'%>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :report_type, class: 'label-control' %>
      <%= f.select :report_type, options_for_select([["QME", "QME"],["AME", "AME"],["IME", "IME"],["SUPP", "SUPP"]]) %>
      <br>
      <%= f.label :interpreter, class: 'label-control' %>
      <%= f.text_field :interpreter, class: 'form-control' %>

      <%= f.label :street_address, class: 'label-control'%>
      <%= f.text_field :street_address, class: 'form-control' %>

      <%= f.label :city, class: 'label-control'%>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state, class: 'label-control'%>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code, class: 'label-control'%>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone, class: 'label-control'%>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :ssn, class: 'label-control'%>
      <%= f.text_field :ssn, class: 'form-control' %>

      <%= f.label :dob, class: 'label-control'%>
      <%= f.text_field :dob, class: 'form-control' %>

      <%= f.label :date_of_injury, class: 'label-control' %>
      <%= f.text_field :date_of_injury, class: 'form-control' %>

      <%= f.label :employer, class: 'label-control'%>
      <%= f.text_field :employer, class: 'form-control' %>

      <%= f.label :claim_number, class: 'label-control'%>
      <%= f.text_field :claim_number, class: 'form-control' %>

      <%= f.label :panel_number, class: 'label-control'%>
      <%= f.text_field :panel_number, class: 'form-control' %>

      <%= f.label :wcab_number, class: 'label-control'%>
      <%= f.text_field :wcab_number, class: 'form-control' %>

      <%= f.label :notes %>
      <%= f.text_area :notes, :rows => 5, class: 'form-control' %>

      <%= f.submit "Save these updates", class: "btn btn-primary" %>
    </div>

    <div class="col-md-4">
      <section class="patient_attorney_info">
        <% if @patient.attorneys.any? %>
        <h4>Patient Attorneys:</h4>

            <%= render partial:"attorneys/edit_attorney", locals: {f: f} %>

        <% end %>
      </section>
    </div>

    <div class="col-md-4">
      <section class="patient_adjuster_info">
        <% if @patient.adjusters.any? %>
        <h4>Patient Adjusters:</h4>

            <%= render partial:"adjusters/edit_adjuster", locals: {f: f} %>

        <% end %>
      </section>
    </div>

    <% end %>
</div>

app/views/patients/index.html.erb
<% if logged_in? %>
<% provide(:title, 'All Patients') %>
<h1>All Patients</h1>

<div class="col-md-2">
	<%= form_tag(patients_path, method: :get, id: 'search-form') do %>
		<%= hidden_field_tag :direction, params[:direction] %>
		<%= hidden_field_tag :sort, params[:sort] %>
		<p>
	  <%= text_field_tag :search, params[:search], placeholder:"Search By Name" %>
	  <%= submit_tag 'Search', name: nil %>
	  </p>
	<% end %>
</div>

<div class="col-md-10">

		<table class="patientTable table">
			<tr>
			<th class="">ID</th>
			<th class="">Name</th>
			<th class="">Date of Injury</th>
			<th class="">Report Type</th>
			<th class="">Updated At</th>
			<th class="">Created At</th>
		</tr>
			<%= render @patients %>
		</table>
	<%= will_paginate @patients %>
	<% end %>
</div>

app/views/patients/new.html.erb
<% provide(:title, 'New Patient') %>
<h1>New Patient Information:</h1>


<div class="row">
	<%= form_for(@patient) do |f| %>
    <%= render 'shared/patient_messages' %>

    <div class="col-md-4 patient_intake">
      <h2>Patient Biographical Information</h3>
      <%= f.label :name, class: 'label-control'%>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :report_type, class: 'label-control report_dropdown' %>
      <%= f.select :report_type, options_for_select([["QME", "QME"],["AME", "AME"],["IME", "IME"],["SUPP", "SUPP"]], [["Other", "Other"]]) %>
      <br>
      
      <%= f.label :interpreter, class: 'label-control' %>
      <%= f.text_field :interpreter, class: 'form-control' %>

      <%= f.label :street_address, class: 'label-control'%>
      <%= f.text_field :street_address, class: 'form-control' %>

      <%= f.label :city, class: 'label-control'%>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state, class: 'label-control'%>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code, class: 'label-control'%>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone, class: 'label-control'%>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :ssn, class: 'label-control'%>
      <%= f.text_field :ssn, class: 'form-control' %>

      <%= f.label :dob, class: 'label-control'%>
      <%= f.text_field :dob, class: 'form-control' %>

      <%= f.label :date_of_injury, class: 'label-control' %>
      <%= f.text_field :date_of_injury, class: 'form-control' %>

      <%= f.label :employer, class: 'label-control'%>
      <%= f.text_field :employer, class: 'form-control' %>

      <%= f.label :claim_number, class: 'label-control'%>
      <%= f.text_field :claim_number, class: 'form-control' %>

      <%= f.label :panel_number, class: 'label-control'%>
      <%= f.text_field :panel_number, class: 'form-control' %>

      <%= f.label :wcab_number, class: 'label-control'%>
      <%= f.text_field :wcab_number, class: 'form-control' %>

      <%= f.label :notes, class: 'label-control'%>
      <%= f.text_area :notes, :rows => 3, class: 'form-control' %>
    </div>

    <div class="col-md-4 patient_intake attorney_creation">
      <h2>Patient Attorneys</h2>
      <%= f.fields_for :attorneys do |attorney_builder| %>
          <%= attorney_builder.label :name %>
          <%= attorney_builder.text_field :name, class: 'form-control' %>

          <%= attorney_builder.label :attorney_type %>
          <%= attorney_builder.select :attorney_type, options_for_select([["Applicant", "Applicant"], ["Defense", "Defense"]]) %>

          <%= attorney_builder.label :firm %>
          <%= attorney_builder.text_field :firm, class: 'form-control' %>

          <%= attorney_builder.label :address %>
          <%= attorney_builder.text_field :address, class: 'form-control' %>

          <%= attorney_builder.label :phone %>
          <%= attorney_builder.text_field :phone, class: 'form-control' %>

          <%= attorney_builder.label :fax %>
          <%= attorney_builder.text_field :fax, class: 'form-control' %>

      <% end %>
          <hr>
          <%= f.fields_for :attorneys do |attorney_builder_1| %>
          <%= attorney_builder_1.label :name %>
          <%= attorney_builder_1.text_field :name, class: 'form-control' %>

          <%= attorney_builder_1.label :attorney_type %>
          <%= attorney_builder_1.select :attorney_type, options_for_select([["Defense", "Defense"], ["Applicant", "Applicant"]]) %>

          <%= attorney_builder_1.label :firm %>
          <%= attorney_builder_1.text_field :firm, class: 'form-control' %>

          <%= attorney_builder_1.label :address %>
          <%= attorney_builder_1.text_field :address, class: 'form-control' %>

          <%= attorney_builder_1.label :phone %>
          <%= attorney_builder_1.text_field :phone, class: 'form-control' %>

          <%= attorney_builder_1.label :fax %>
          <%= attorney_builder_1.text_field :fax, class: 'form-control' %>

      <% end %>
      </div>

    <div class="col-md-4 patient_intake adjuster_creation">
      <h2>Patient Adjuster</h2>
      <%= f.fields_for :adjusters do |aj| %>
        <%= aj.label :name %>
        <%= aj.text_field :name, class: 'form-control' %>

        <%= aj.label :agency %>
        <%= aj.text_field :agency, class: 'form-control' %>

        <%= aj.label :address %>
        <%= aj.text_field :address, class: 'form-control' %>

        <%= aj.label :phone %>
        <%= aj.text_field :phone, class: 'form-control' %>

        <%= aj.label :fax %>
        <%= aj.text_field :fax, class: 'form-control' %>

      <% end %>
    </div>
</div>

<div class="row"> 
  <div class="col-md-3 col-md-offset-2">
    <%= f.submit "Save this Patient", class: "btn btn-primary" %>
  </div>
</div>
  <% end %>
</div>

app/views/patients/show.html.erb
<% provide(:title, @patient.name) %>

<div class="row">
	<div class="options_row center">
    <p>Use these buttons to edit or remove the patient</p>
    <%= link_to "Edit Patient", edit_patient_path, class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete Patient", @patient, method: :delete,:data => {confirm: 'Are you sure you want to delete this patient? There is NO recovery option!'}, class: "btn btn-xs btn-danger" %>
	</div>
  <hr>
</div>


<div class="row">
  <div class="col-md-6">
    <div class="templates_box center">
      <h4>Templates</h4>
      <p>Clicking any button will start a download of the relevant template for this patient</p>
      <p>
      <%= link_to "Appointment Confirmation", patient_appointment_confirmation_path(:patient_id => @patient.id), class: "btn btn-xs btn-primary" %>
      <%= link_to "Depo Invoice", patient_depo_invoice_path(:patient_id => @patient.id), class: "btn btn-xs btn-primary" %>
      <%= link_to "Depo Confirmation", patient_depo_confirmation_path(:patient_id => @patient.id), class: "btn btn-xs btn-primary" %>
      <%= link_to "Action Items", patient_action_items_path(:patient_id => @patient.id), class: "btn btn-xs btn-primary" %>
      </p>
    </div>
    <div class="action_items center">
      <h4>Action Items</h4>
      <p>ETC</p>
    </div>
  </div>

  <div class="col-md-6">
    <section class="patient_appointment_info center">
      <h4>Upcoming Appointments:</h4>
      <% if @patient.appointments.any? %>
        <%= render @appointments %>
      <% end %>
      <%= link_to "New Appointment", new_patient_appointment_path(:patient_id => @patient.id), class: "btn btn-xs btn-primary" %>
    </section>
  </div>

  
</div>

<hr>

<div class="row">
  <aside class="col-md-4">
    <section class="patient_info">
      <h1><%= @patient.name %></h1>
      <p>Report: <strong><%= @patient.report_type %></strong></p>
      <p>Interpreter: <strong><%= @patient.interpreter %></strong></p>
      <hr>

        <h4>Report Information:</h4>
        <p>Claim Number: <%= @patient.claim_number %>
        <p>Panel Number: <%= @patient.panel_number %>
        <p>WCAB Number: <%= @patient.wcab_number %> 
        <hr>

        <h5>Date of Injury:</h5>
        <p><%=@patient.date_of_injury %></p>

        <h5>Address:</h5>
        <p><%= @patient.street_address %></p>
        <p><%= @patient.city %> <%= @patient.state %>, <%= @patient.zip_code %></p>

        <h5>Phone Number:</h5><p><%= @patient.phone %></p>
        <h5>SSN:</h5><p><%= @patient.ssn %> </p>
        <h5>Date Of Birth:</h5><p><%= @patient.dob %></p>
        
        <hr>
        <h5>Notes:</h5><p><%= @patient.notes %></p>    
        </section>
  </aside>

  <div class="col-md-4">
    <section class="patient_attorney_info">
      <% if @patient.attorneys.any? %>
      <h5>Patient Attorneys:</h5>
        <%= render @attorneys %>
      <% end %>
    </section>
  </div>

  <div class="col-md-4">
    <section class="patient_adjuster_info">
      <% if @patient.adjusters.any? %>
      <h5>Patient Adjusters:</h5>
        <%= render @adjusters %>
        <% end %>
    </section>
  </div>

</div>