config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get '/calendar', to: 'static_pages#calendar'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]

  # Need Routes for all models 

  #Patient
  resources :patients do
    resources :appointments, only: [:index, :show, :new, :create]
    # Templates
    # Allows for /patient/:id/TEMPLATE
    get :appointment_confirmation, format: 'docx'
    get :depo_invoice, format: 'docx'
    get :depo_confirmation, format: 'docx'
    get :action_items, format: 'docx'
  end

  #Appointment
  resources :appointments

  #Attorney
  resources :attorneys

  #Adjuster
  #resources :adjuster

end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :patient
	validates :patient_id, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @patient = Patient.find(params[:patient_id])
    @appointment = Appointment.new
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @appointment = @patient.appointments.build(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment }
        format.json { render :show, status: :ok, location: @appointment }
        flash[:success] = "Appointment Updated"
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Appointment.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def appointment_params
      params.require(:appointment).permit(:office, :address, :appointment_type, :status, :start_time, :patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<li id="patient_appointments-<%= appointment.id %>">
	<p><strong>Type</strong>: <%= appointment.appointment_type %> </p>
	<p><strong>Office</strong>: <%= appointment.office %> <strong>Status</strong>: <%= appointment.status %></p>
	<p><strong>Time</strong>: <%= appointment.start_time %></p>
	<%= link_to 'Edit', edit_appointment_path %>
	<hr>
</li>

app/views/appointments/_calendar.html.erb
<%= month_calendar events: @appointments do |date, appointments| %>
  <%= date.day %>

  <% appointments.each do |event| %>
    <div class="patient_calendar_appointment">
	    <p><%= link_to event.patient.name, patient_path(event) %></p>
	    <p><%= event.appointment_type %></p>
      <p><%= event.start_time.strftime("%I:%M %P") %>   <%= link_to "Edit", edit_appointment_path(event) %>   <%= link_to "View", appointment_path(event) %></p>

      <hr>
    </div>
  <% end %>
<% end %>

app/views/appointments/_form.html.erb
<%= form_for [@patient, @appointment] do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag "patient_id", @patient.id %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :office %><br>
    <%= f.text_field :office %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :appointment_type %><br>
    <%= f.text_field :appointment_type %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<%= form_for @appointment do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :office %><br>
    <%= f.text_field :office %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :appointment_type %><br>
    <%= f.text_field :appointment_type %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/index.html.erb
<% if logged_in? %>
<% provide(:title, 'Appointments') %>

<h3>Monthly Appointments</h3>



<div id="appointment_calendar">
  <%= render partial: "calendar", locals: {appointments: @appointments} %>
</div>

<table class="table table-span">
  <thead>
    <tr>
      <th>Patient</th>
      <th>Start time</th>
      <th>Office</th>
      <th>Appointment Type</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.office %></td>
        <td><%= appointment.appointment_type %></td>

        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to appointment, remote: true, method: :delete,  data: { confirm: 'This will permanently delete this appointment. Are you sure?' } do %>
            <link>Delete</link>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>




<% end %>

app/views/appointments/index.js.erb
$("#appointment_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @appointments}) %>");

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
	<%= render partial: 'form', locals: {appointment: @appointment, patient: @patient} %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.name %>
</p>

<p>
  <strong>Office:</strong>
  <%= @appointment.office %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>Address:</strong>
  <%= @appointment.address %>
</p>

<p>
  <strong>Appointment_type:</strong>
  <%= @appointment.appointment_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @appointment.status %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>