config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get '/calendar', to: 'static_pages#calendar'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]

  # Need Routes for all models 

  #Patient
  resources :patients do
    resources :appointments, only: [:index, :show, :new, :create]
    # Templates
    # Allows for /patient/:id/TEMPLATE
    get :appointment_confirmation, format: 'docx'
    get :depo_invoice, format: 'docx'
    get :depo_confirmation, format: 'docx'
    get :action_items, format: 'docx'
  end

  #Appointment
  resources :appointments

  #Attorney
  resources :attorneys

  #Adjuster
  #resources :adjuster

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	 <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to 'ADMD', root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Patients<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create Patient", new_patient_url, data: { turbolinks: false } %></li>
              <li><%= link_to "View All", patients_path %></li>
            </ul>
          </li>
        <li><%= link_to "Appointments", appointments_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | ADMD</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>